package CricketManagementSystem;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
	initComponents();
	setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        showIPLDetails = new javax.swing.JMenuItem();
        addIPLData = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        showMatches = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        showPlayers = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        showBattingStatistics = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        showBowlingStats = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        showSeasonDetails = new javax.swing.JMenuItem();
        editSeasonDetails = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        editStadiumDetails = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        showStadiums = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        showStandings = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        showTeamOwners = new javax.swing.JMenuItem();
        editTeamOwnerDetails = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addUpdateDelete = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        showTeamDetails = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        exitApplication = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        AboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cricket Management System [Dashboard]");
        setBackground(new java.awt.Color(0, 102, 102));
        setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        setName("home"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_page_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 1920, 1080));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));

        jMenu8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\IPL.png")); // NOI18N
        jMenu8.setText("IPL");
        jMenu8.setFocusable(false);
        jMenu8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        showIPLDetails.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        showIPLDetails.setText("Show IPL Details");
        showIPLDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showIPLDetailsActionPerformed(evt);
            }
        });
        jMenu8.add(showIPLDetails);

        addIPLData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addIPLData.setText("Edit IPL Details");
        addIPLData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIPLDataActionPerformed(evt);
            }
        });
        jMenu8.add(addIPLData);

        jMenuBar1.add(jMenu8);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/matches.png"))); // NOI18N
        jMenu3.setText("Matches");
        jMenu3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jMenu3.add(jSeparator9);

        showMatches.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showMatches.setText("All Match Details");
        showMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMatchesActionPerformed(evt);
            }
        });
        jMenu3.add(showMatches);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\Players.png")); // NOI18N
        jMenu1.setText("Player");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jMenu1.add(jSeparator1);

        showPlayers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showPlayers.setText("All Player Details");
        showPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPlayersActionPerformed(evt);
            }
        });
        jMenu1.add(showPlayers);

        jMenuBar1.add(jMenu1);

        jMenu9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\Batting.png")); // NOI18N
        jMenu9.setText("Batting Stats");
        jMenu9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        showBattingStatistics.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showBattingStatistics.setText("Show Batting Statistics ");
        showBattingStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBattingStatisticsActionPerformed(evt);
            }
        });
        jMenu9.add(showBattingStatistics);

        jMenuBar1.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\Bowling.png")); // NOI18N
        jMenu10.setText("Bowling Stats");
        jMenu10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        showBowlingStats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showBowlingStats.setText("Show Bowling Statistics");
        showBowlingStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBowlingStatsActionPerformed(evt);
            }
        });
        jMenu10.add(showBowlingStats);

        jMenuBar1.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Calendar.png"))); // NOI18N
        jMenu11.setText("Seasons");

        showSeasonDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showSeasonDetails.setText("Season Details");
        showSeasonDetails.setPreferredSize(new java.awt.Dimension(234, 31));
        showSeasonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSeasonDetailsActionPerformed(evt);
            }
        });
        jMenu11.add(showSeasonDetails);

        editSeasonDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editSeasonDetails.setText("Edit Season Details");
        editSeasonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSeasonDetailsActionPerformed(evt);
            }
        });
        jMenu11.add(editSeasonDetails);

        jMenuBar1.add(jMenu11);

        jMenu5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\Stadium.png")); // NOI18N
        jMenu5.setText("Stadium");
        jMenu5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        editStadiumDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editStadiumDetails.setText("Edit Stadium Details");
        editStadiumDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStadiumDetailsActionPerformed(evt);
            }
        });
        jMenu5.add(editStadiumDetails);
        jMenu5.add(jSeparator15);

        showStadiums.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showStadiums.setText("All Stadium Details");
        showStadiums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStadiumsActionPerformed(evt);
            }
        });
        jMenu5.add(showStadiums);

        jMenuBar1.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\standings.png")); // NOI18N
        jMenu7.setText("Standings ");
        jMenu7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        showStandings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showStandings.setText("Standings Details");
        showStandings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStandingsActionPerformed(evt);
            }
        });
        jMenu7.add(showStandings);

        jMenuBar1.add(jMenu7);

        jMenu12.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\Team owner 2.png")); // NOI18N
        jMenu12.setText("Team Owners");
        jMenu12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        showTeamOwners.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showTeamOwners.setText("Team Owner Details");
        showTeamOwners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTeamOwnersActionPerformed(evt);
            }
        });
        jMenu12.add(showTeamOwners);

        editTeamOwnerDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editTeamOwnerDetails.setText("Edit Team Owner Details");
        editTeamOwnerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTeamOwnerDetailsActionPerformed(evt);
            }
        });
        jMenu12.add(editTeamOwnerDetails);

        jMenuBar1.add(jMenu12);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Desktop\\Coding projects\\CRICKET STATS MANAGER\\Cricket-Management-System\\build\\classes\\Icons\\Teams.png")); // NOI18N
        jMenu2.setText("Team");
        jMenu2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        addUpdateDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addUpdateDelete.setText("Edit Team Details");
        addUpdateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpdateDeleteActionPerformed(evt);
            }
        });
        jMenu2.add(addUpdateDelete);
        jMenu2.add(jSeparator4);

        showTeamDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showTeamDetails.setText("Show All Teams Details");
        showTeamDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTeamDetailsActionPerformed(evt);
            }
        });
        jMenu2.add(showTeamDetails);

        jMenuBar1.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        jMenu6.setText("Exit");
        jMenu6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu6.add(Logout);
        jMenu6.add(jSeparator16);

        exitApplication.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitApplication.setText("Exit Application");
        exitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApplicationActionPerformed(evt);
            }
        });
        jMenu6.add(exitApplication);
        jMenu6.add(jSeparator2);

        AboutUs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        jMenu6.add(AboutUs);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
	int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout", "Select", JOptionPane.YES_NO_OPTION);
	if (a == 0) {
	    setVisible(false);
	    new Login().setVisible(true);
	}
    }//GEN-LAST:event_LogoutActionPerformed

    private void exitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApplicationActionPerformed
	int a = JOptionPane.showConfirmDialog(null, "Do you want to Close Application", "Select", JOptionPane.YES_NO_OPTION);
	if (a == 0) {
	    System.exit(0);
	}
    }//GEN-LAST:event_exitApplicationActionPerformed

    private void showPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPlayersActionPerformed
	new ShowPlayerDetails().setVisible(true);
    }//GEN-LAST:event_showPlayersActionPerformed

    private void addUpdateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpdateDeleteActionPerformed
	new EditTeamDetails().setVisible(true);
    }//GEN-LAST:event_addUpdateDeleteActionPerformed

    private void showTeamDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTeamDetailsActionPerformed
	new ShowTeamDetails().setVisible(true);
    }//GEN-LAST:event_showTeamDetailsActionPerformed

    private void showMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMatchesActionPerformed
	new ShowMatchDetails().setVisible(true);
    }//GEN-LAST:event_showMatchesActionPerformed

    private void editStadiumDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStadiumDetailsActionPerformed
	new EditStadiumDetails().setVisible(true);
    }//GEN-LAST:event_editStadiumDetailsActionPerformed

    private void showStadiumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStadiumsActionPerformed
        new ShowStadiumDetails().setVisible(true);
    }//GEN-LAST:event_showStadiumsActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_AboutUsActionPerformed

    private void showIPLDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showIPLDetailsActionPerformed
        new ShowIPLDetails().setVisible(true);
    }//GEN-LAST:event_showIPLDetailsActionPerformed

    private void showBattingStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBattingStatisticsActionPerformed
        new ShowBattingStatistics().setVisible(true);
    }//GEN-LAST:event_showBattingStatisticsActionPerformed

    private void showBowlingStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBowlingStatsActionPerformed
        new ShowBowlingStatistics().setVisible(true);
    }//GEN-LAST:event_showBowlingStatsActionPerformed

    private void showStandingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStandingsActionPerformed
       new ShowStandingsDetails().setVisible(true);
    }//GEN-LAST:event_showStandingsActionPerformed

    private void showSeasonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSeasonDetailsActionPerformed
        new ShowSeasonDetails().setVisible(true);
    }//GEN-LAST:event_showSeasonDetailsActionPerformed

    private void editSeasonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSeasonDetailsActionPerformed
        new EditSeasonDetails().setVisible(true);
    }//GEN-LAST:event_editSeasonDetailsActionPerformed

    private void showTeamOwnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTeamOwnersActionPerformed
        new ShowTeamOwnerDetails().setVisible(true);
    }//GEN-LAST:event_showTeamOwnersActionPerformed

    private void editTeamOwnerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTeamOwnerDetailsActionPerformed
        new EditTeamOwnerDetails().setVisible(true);
    }//GEN-LAST:event_editTeamOwnerDetailsActionPerformed

    private void addIPLDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIPLDataActionPerformed
        new EditIPLDetails().setVisible(true);
    }//GEN-LAST:event_addIPLDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Home().setVisible(true);
	    }
	});
    }

    private void setIcon() {
	setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUs;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem addIPLData;
    private javax.swing.JMenuItem addUpdateDelete;
    private javax.swing.JMenuItem editSeasonDetails;
    private javax.swing.JMenuItem editStadiumDetails;
    private javax.swing.JMenuItem editTeamOwnerDetails;
    private javax.swing.JMenuItem exitApplication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem showBattingStatistics;
    private javax.swing.JMenuItem showBowlingStats;
    private javax.swing.JMenuItem showIPLDetails;
    private javax.swing.JMenuItem showMatches;
    private javax.swing.JMenuItem showPlayers;
    private javax.swing.JMenuItem showSeasonDetails;
    private javax.swing.JMenuItem showStadiums;
    private javax.swing.JMenuItem showStandings;
    private javax.swing.JMenuItem showTeamDetails;
    private javax.swing.JMenuItem showTeamOwners;
    // End of variables declaration//GEN-END:variables
}
